# Generated by Django 4.2.3 on 2023-07-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('bKash', 'bKash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad')], max_length=100, null=True),
        ),
    ]
