# Generated by Django 4.2.3 on 2023-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment_account_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
