# Generated by Django 4.2.3 on 2023-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_schedules_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
