# Generated by Django 4.2.3 on 2023-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_schedules_schedule_alter_doctor_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='app.schedule'),
        ),
    ]
