# Generated by Django 4.2.3 on 2023-07-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_invoice_home_service_invoice_home_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='home_service_available',
            field=models.BooleanField(default=False),
        ),
    ]
